import { FormEvent, useState } from 'react'
import { Link, Route, Routes } from 'react-router-dom'
import './styles.css'

type LocationId = 'nirmala' | 'jss'

const locations: Record<LocationId, { name: string; detail: string; days: string; hours: string }> = {
  nirmala: { name: 'Nirmala Multi Specialty Hospital', detail: 'Mysuru', days: 'Monday to Saturday', hours: 'Mon/Wed/Fri: 9:30 AM – 1:00 PM · Tue/Thu/Sat: 9:30 AM – 7:00 PM' },
  jss: { name: 'JSS Hospital, Chamarajanagar', detail: 'Chamarajanagar', days: 'Monday, Wednesday and Friday', hours: '3:00 PM – 7:00 PM' },
}

function Header() {
  return <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">B</span><span><strong>Dr. Bharathi P</strong><small>Obstetrician & Gynaecologist</small></span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#locations">Locations</a><a href="#appointments" className="nav-cta">Request appointment</a></nav></header>
}

function AppointmentWizard() {
  const [step, setStep] = useState(1)
  const [location, setLocation] = useState<LocationId>('nirmala')
  const [timePreference, setTimePreference] = useState('')
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  if (submitted) return <section className="confirmation" aria-live="polite"><p className="eyebrow">Request preview</p><h2>Almost ready for appointment requests</h2><p>This is the future confirmation screen. Appointment submission will connect to the secure server once the database is configured. A request is never an appointment confirmation.</p><button className="button button-secondary" onClick={() => { setSubmitted(false); setStep(1) }}>Start another request</button></section>
  return <section className="wizard" aria-labelledby="wizard-title"><div className="wizard-heading"><div><p className="eyebrow">Appointment requests</p><h2 id="wizard-title">Request an appointment</h2></div><span className="step-count">Step {step} of 4</span></div><ol className="steps" aria-label="Appointment request progress">{['Location', 'Preference', 'Your details', 'Review'].map((label, index) => <li key={label} className={index + 1 <= step ? 'active' : ''}>{label}</li>)}</ol><form onSubmit={submit}>
    {step === 1 && <fieldset><legend>Where would you like to consult?</legend><div className="choice-grid">{(Object.entries(locations) as [LocationId, typeof locations[LocationId]][]).map(([id, place]) => <label className={`choice-card ${location === id ? 'selected' : ''}`} key={id}><input type="radio" name="location" value={id} checked={location === id} onChange={() => { setLocation(id); setTimePreference('') }} /><strong>{place.name}</strong><span>{place.detail}</span></label>)}</div></fieldset>}
    {step === 2 && <fieldset><legend>Choose a preferred date and time</legend><p className="schedule-note">Routine appointments are unavailable on Sundays. Selected times are requests and require clinic confirmation.</p><div className="form-grid"><label>Preferred date<input type="date" required /></label><label>Preferred time<select value={timePreference} onChange={(event) => setTimePreference(event.target.value)} required><option value="" disabled>Select a preferred time</option>{location === 'nirmala' && <option value="MORNING">Morning preference</option>}<option value="AFTERNOON">Afternoon preference</option>{location === 'nirmala' && <option value="EVENING">Evening preference</option>}{location === 'jss' && <option value="EVENING">Evening preference</option>}</select></label></div><p className="helper">Your selected time is a preference. It is confirmed only after the doctor accepts your request.</p></fieldset>}
    {step === 3 && <fieldset><legend>Tell us how to reach you</legend><div className="form-grid"><label>Full name<input autoComplete="name" required /></label><label>Age<input type="number" min="0" max="120" required /></label><label>Phone number<input type="tel" inputMode="numeric" placeholder="10-digit mobile number" required /></label><label>Email <span className="optional">(optional)</span><input type="email" autoComplete="email" /></label></div><label>Reason for visit<select defaultValue="" required><option value="" disabled>Select a reason</option><option>Routine consultation</option><option>Pregnancy consultation</option><option>Follow-up</option><option>Menstrual concerns</option><option>Other</option></select></label><label>Anything else you would like the doctor to know? <span className="optional">(optional)</span><textarea rows={4} placeholder="Information specific to this appointment request" /></label></fieldset>}
    {step === 4 && <fieldset><legend>Review your request</legend><div className="review-card"><p><strong>Location</strong><br />{locations[location].name}</p><p><strong>Important</strong><br />Submitting creates an appointment request only. The clinic must confirm it.</p></div><label className="consent"><input type="checkbox" required /> <span>I understand that this is an appointment request, not emergency care. I agree to the clinic using my details to coordinate this request.</span></label></fieldset>}
    <div className="wizard-actions"><button type="button" className="button button-secondary" onClick={() => setStep((value) => Math.max(1, value - 1))} disabled={step === 1}>Back</button>{step < 4 ? <button type="button" className="button" onClick={() => setStep((value) => Math.min(4, value + 1))}>Continue</button> : <button className="button" type="submit">Preview request</button>}</div>
  </form></section>
}

function HomePage() {
  return <div id="top"><Header /><main><section className="hero"><div className="hero-copy"><p className="eyebrow">Women’s healthcare</p><h1>Care that begins with listening.</h1><p className="hero-text">Request an appointment with Dr. Bharathi P for compassionate obstetric and gynaecological care.</p><div className="hero-actions"><a className="button" href="#appointments">Request an appointment</a><a className="text-link" href="#locations">View practice locations <span aria-hidden="true">→</span></a></div></div><div className="hero-panel"><span className="panel-icon" aria-hidden="true">✦</span><p>Appointments are reviewed by the clinic before they are confirmed.</p></div></section>
    <section id="about" className="about"><p className="eyebrow">About the practice</p><h2>Professional, personal and patient-centred.</h2><p>Dr. Bharathi P is an Obstetrician and Gynaecologist. This practice website is designed to make it simpler to find a consultation location and send an appointment request.</p><div className="education"><p><strong>Medical education</strong></p><p>MBBS — Mysore Medical College, Mysuru</p><p>Postgraduate medical training — KMC, Mangalore</p><p>Additional training in infertility care — Medline Academy</p></div></section>
    <section id="locations" className="locations section"><div className="section-heading"><div><p className="eyebrow">Practice locations</p><h2>Find the right consultation location</h2></div><p>Routine appointments are not offered on Sundays.</p></div><div className="location-grid">{(Object.entries(locations) as [LocationId, typeof locations[LocationId]][]).map(([id, place]) => <article className="location-card" key={id}><span className="location-number">0{id === 'nirmala' ? '1' : '2'}</span><h3>{place.name}</h3><p>{place.detail}</p><dl><dt>Consultation days</dt><dd>{place.days}</dd><dt>Consultation hours</dt><dd><span className="hours-tag confirmed-hours">{place.hours}</span></dd></dl><a href="#appointments" onClick={() => setTimeout(() => document.querySelector<HTMLInputElement>(`input[value="${id}"]`)?.click(), 0)}>Request appointment <span aria-hidden="true">→</span></a></article>)}</div></section>
    <section id="appointments" className="appointment-section section"><AppointmentWizard /></section><p className="emergency-notice"><strong>Emergency notice:</strong> This website is for appointment requests and general information only. It is not an emergency medical service. In an emergency, contact local emergency services or visit the nearest emergency department.</p></main><footer><div><strong>Dr. Bharathi P</strong><p>Obstetrician & Gynaecologist</p></div><p>Appointment requests are reviewed by the clinic. Not for emergencies.</p></footer></div>
}

function AdminPlaceholder() { return <main className="admin-placeholder"><h1>Admin dashboard</h1><p>Secure sign-in and appointment management will be added next.</p><Link to="/">Return to the public site</Link></main> }
export default function App() { return <Routes><Route path="/" element={<HomePage />} /><Route path="/admin/*" element={<AdminPlaceholder />} /></Routes> }
